### ISSUE TITLE
You continue it?

### ISSUE THREAD

**Issue by xxCherry** [DDDinggo22/Osu-Bot#2]
You continue it? Or say me how to find timer pointer please.

**Comment by TheCodingNina** [comment]
Yes I am still continuing it. The timer pointer has been updated in my Test-Environment branch. I will update the other branches soon, as the Updates/Improvements are proving to be stable enough for the master build.  :)

**Comment by xxCherry** [comment]
Okay i testing it x)

**Comment by xxCherry** [comment]
Ohh, cursor looks legit but he not smart :) It so buggy.

**Comment by TheCodingNina** [comment]
What do you exactly mean with buggy? Can you describe it for me? Because for me it seems to work fine.

**Comment by xxCherry** [comment]
okay i upload video on youtube

**Comment by xxCherry** [comment]
https://youtu.be/eyVyHobUECg

**Comment by TheCodingNina** [comment]
It looks like an issue with the threads being slow. The cursor is being updated to slow/the time is being read to slow. I run i7-7700k @ 4.8Ghz so thread speeds are not a issue I have tested.

If you cloned the source, see if increasing the thread sleep time (to a few milliseconds) improves performance.

I will increase the time on the source because I don't need the treads to be that fast tbh.

**Comment by xxCherry** [comment]
it? "this_thread::sleep_for(chrono::microseconds(100));"
or it "this_thread::sleep_for(chrono::milliseconds(12));"
Sorry, I do not really understand.

**Comment by TheCodingNina** [comment]
yes by changing those in the "CursorMovement.h" you can change time between cursor updates.
And in "OsuBot.h" in "AutoPlay(wstring nowPlaying)" you can change time for main autoplay loop.

**Comment by TheCodingNina** [comment]
"this_thread::sleep_for(chrono::milliseconds(12))" is the delay for click and release mouse/keyboard key presses.

**Comment by xxCherry** [comment]
Does not help :'( Fucking slowest processor.
