### ISSUE TITLE
cursor freeze

### ISSUE THREAD

**Issue by xxCherry** [DDDinggo22/Osu-Bot#6]

**Comment by TheCodingNina** [comment]
If you were using the latest version, I had used uppercase letters in the values for the TimerPointer. As it appeared that I didn't had anything that would convert them to lowercase before searching for the TimerAddress, It would gave wrong addresses (because upper and lowercase letters have different hex values.) Causing the cursor to freeze in place.

So I have updated the bot to be able to read TimerPointer with uppercase hexadecimal values.
This should have fixed it. Let me know if it is still not working.

**Comment by xxCherry** [comment]
it not fixed my cursor

**Comment by TheCodingNina** [comment]
It appears that the 'debug' build works fine but the 'release' build is not getting the correct address.
If you want you can clone/fork/download the source and compile it for yourself to see if the 'debug' build works better than the release.

I will do some research on this and hopefully it is a quick to fix problem.

**Comment by xxCherry** [comment]
'debug' build too.
